version: '3.8'

volumes:
    EcommerceDb:

networks:
    mysqlNET:
    ecommerceNET:

services:
    mysql:
        image: "mysql:5.7"
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - "EcommerceDb:/var/lib/mysql"
        networks:
            - mysqlNET
        environment:

    ecommerce:
        build:
            context:
            dockerfile: Dockerfile
        container_name: ecommerce
        ports:
            - 5000:80
        networks:
            - mysqlNET
            - ecommerceNET
        environment:
            - DBHOST=mysql
        depends_on:
            - mysql